apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: hf-token
    creationPolicy: Owner
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: hf-token
