apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scale23x-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:pauldotyu/scale23x-demo.git
    targetRevision: HEAD
    path: manifests/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
